version: "3"
services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    networks:
      - app-network
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile.consumer
    container_name: consumer
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    networks:
      - app-network
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile.producer
    container_name: producer
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
